import type { CallSession, BattleCard, Objection, Analytics, HealthStatus, DailyAnalytics, LLMProvider } from '@/types'

export const mockHealth: HealthStatus = {
  status: 'ok',
  active_calls: 3,
  current_provider: 'groq',
  uptime_seconds: 86400,
}

export const mockActiveCalls: Record<string, CallSession> = {
  'CA123': {
    call_sid: 'CA123',
    phone_number: '+919876543210',
    state: 'discovery',
    outcome: 'in_progress',
    started_at: new Date(Date.now() - 120000).toISOString(),
    duration_seconds: 120,
    transcript: [
      { speaker: 'ai', text: 'Hello! This is Aarav from Career Launchpad. How can I help you today?', timestamp: new Date(Date.now() - 120000).toISOString(), state: 'opening' },
      { speaker: 'user', text: 'Hi, I saw your ad about career coaching. What exactly do you offer?', timestamp: new Date(Date.now() - 110000).toISOString() },
      { speaker: 'ai', text: 'We offer personalized career coaching for working professionals looking to switch careers or accelerate growth. Our 12-week program includes 1-on-1 sessions, resume building, and interview prep. May I ask what your current situation is?', timestamp: new Date(Date.now() - 100000).toISOString(), state: 'discovery' },
      { speaker: 'user', text: 'I am currently in IT but want to move to product management. Is that something you help with?', timestamp: new Date(Date.now() - 85000).toISOString() },
      { speaker: 'ai', text: 'Absolutely! IT to product management is one of our most successful tracks. We have helped over 200 professionals make that exact transition. What is your biggest concern about this switch?', timestamp: new Date(Date.now() - 70000).toISOString(), state: 'discovery' },
    ],
    llm_provider: 'groq',
    llm_model: 'llama-3.3-70b',
    last_ai_message: 'Absolutely! IT to product management is one of our most successful tracks...',
  },
  'CA124': {
    call_sid: 'CA124',
    phone_number: '+919812345678',
    state: 'objection',
    outcome: 'in_progress',
    started_at: new Date(Date.now() - 300000).toISOString(),
    duration_seconds: 300,
    transcript: [
      { speaker: 'ai', text: 'Namaste! Welcome to GrowthMind Coaching. How may I assist you today?', timestamp: new Date(Date.now() - 300000).toISOString(), state: 'opening' },
      { speaker: 'user', text: 'I am looking for a leadership coach for my team. We are a startup of 15 people.', timestamp: new Date(Date.now() - 290000).toISOString() },
      { speaker: 'ai', text: 'That sounds exciting! We work with several startups in the 10-50 employee range. Our leadership coaching focuses on building emotional intelligence and decision-making skills. What challenges is your team facing currently?', timestamp: new Date(Date.now() - 280000).toISOString(), state: 'discovery' },
      { speaker: 'user', text: 'Communication issues mostly. People are not on the same page.', timestamp: new Date(Date.now() - 260000).toISOString() },
      { speaker: 'ai', text: 'Communication gaps are very common at the 15-person stage. We have a specific module called "Alignment Architecture" that addresses exactly this. It includes weekly workshops and daily check-in frameworks. The investment is Rs 25,000 per month for your team size.', timestamp: new Date(Date.now() - 240000).toISOString(), state: 'pitch' },
      { speaker: 'user', text: 'Rs 25,000 seems quite expensive for us right now. We are bootstrapped.', timestamp: new Date(Date.now() - 220000).toISOString() },
      { speaker: 'ai', text: 'I completely understand budget constraints at the bootstrapped stage. Many of our clients felt the same way initially. Would it help if we started with a pilot program at Rs 12,000 for the first month so you can see the ROI before committing?', timestamp: new Date(Date.now() - 200000).toISOString(), state: 'objection' },
    ],
    llm_provider: 'groq',
    llm_model: 'llama-3.3-70b',
    last_ai_message: 'Would it help if we started with a pilot program at Rs 12,000...',
  },
  'CA125': {
    call_sid: 'CA125',
    phone_number: '+919999888877',
    state: 'pitch',
    outcome: 'in_progress',
    started_at: new Date(Date.now() - 45000).toISOString(),
    duration_seconds: 45,
    transcript: [
      { speaker: 'ai', text: 'Hello! Thank you for calling Excellence Academy. I am Priya, your admission counselor. How can I help you today?', timestamp: new Date(Date.now() - 45000).toISOString(), state: 'opening' },
      { speaker: 'user', text: 'Hi Priya, I want to know about your UPSC coaching program.', timestamp: new Date(Date.now() - 40000).toISOString() },
      { speaker: 'ai', text: 'Excellent choice! Our UPSC Foundation Program is a comprehensive 1-year course covering Prelims, Mains, and Interview preparation. We have both online and offline batches. Which mode would you prefer?', timestamp: new Date(Date.now() - 35000).toISOString(), state: 'pitch' },
    ],
    llm_provider: 'openai',
    llm_model: 'gpt-4o',
    last_ai_message: 'Excellent choice! Our UPSC Foundation Program is a comprehensive 1-year course...',
  },
}

export const generateMockHistory = (): CallSession[] => [
  {
    call_sid: 'CA100',
    phone_number: '+919876543201',
    state: 'ended',
    outcome: 'booked',
    started_at: new Date(Date.now() - 86400000 + 3600000).toISOString(),
    ended_at: new Date(Date.now() - 86400000 + 5400000).toISOString(),
    duration_seconds: 1800,
    transcript: [
      { speaker: 'ai', text: 'Hello! Welcome to SuccessPath Coaching. How can I assist you today?', timestamp: new Date(Date.now() - 86400000 + 3600000).toISOString(), state: 'opening' },
      { speaker: 'user', text: 'I want to improve my public speaking skills. I have a big presentation coming up.', timestamp: new Date(Date.now() - 86400000 + 3700000).toISOString() },
      { speaker: 'ai', text: 'That is a great goal! Public speaking can be transformative for your career. Our "Confident Speaker" program has helped over 500 professionals. Can you tell me more about your presentation?', timestamp: new Date(Date.now() - 86400000 + 3800000).toISOString(), state: 'discovery' },
      { speaker: 'user', text: 'It is a board presentation. I am terrified.', timestamp: new Date(Date.now() - 86400000 + 3900000).toISOString() },
      { speaker: 'ai', text: 'Board presentations are high-stakes, and feeling nervous is completely normal. Our intensive 4-week program includes mock board sessions, breathing techniques, and slide structuring. Shall I book a free assessment call?', timestamp: new Date(Date.now() - 86400000 + 4000000).toISOString(), state: 'pitch' },
      { speaker: 'user', text: 'Yes, please book it for tomorrow.', timestamp: new Date(Date.now() - 86400000 + 4100000).toISOString() },
      { speaker: 'ai', text: 'Perfect! I have booked your assessment call for tomorrow at 11 AM. You will receive a calendar invite shortly. Is there anything else I can help with?', timestamp: new Date(Date.now() - 86400000 + 4200000).toISOString(), state: 'close' },
    ],
    llm_provider: 'groq',
    llm_model: 'llama-3.3-70b',
    last_ai_message: 'Perfect! I have booked your assessment call for tomorrow at 11 AM.',
    recording_url: 'https://example.com/rec/CA100',
  },
  {
    call_sid: 'CA101',
    phone_number: '+919876543202',
    state: 'ended',
    outcome: 'declined',
    started_at: new Date(Date.now() - 172800000 + 7200000).toISOString(),
    ended_at: new Date(Date.now() - 172800000 + 8400000).toISOString(),
    duration_seconds: 1200,
    transcript: [
      { speaker: 'ai', text: 'Hello! This is Mindful Growth Academy. How can I help you?', timestamp: new Date(Date.now() - 172800000 + 7200000).toISOString(), state: 'opening' },
      { speaker: 'user', text: 'I am looking for stress management coaching for my employees.', timestamp: new Date(Date.now() - 172800000 + 7300000).toISOString() },
      { speaker: 'ai', text: 'We specialize in corporate wellness programs. Our stress management coaching includes group sessions and individual counseling. What is your team size?', timestamp: new Date(Date.now() - 172800000 + 7400000).toISOString(), state: 'discovery' },
      { speaker: 'user', text: 'About 50 employees. But I think this is too expensive for us right now.', timestamp: new Date(Date.now() - 172800000 + 7500000).toISOString() },
      { speaker: 'ai', text: 'I understand budget is a concern. For 50 employees, we have a special corporate rate. Would you like to hear about it?', timestamp: new Date(Date.now() - 172800000 + 7600000).toISOString(), state: 'objection' },
      { speaker: 'user', text: 'No thanks, maybe later.', timestamp: new Date(Date.now() - 172800000 + 7700000).toISOString() },
      { speaker: 'ai', text: 'No problem at all! Feel free to reach out whenever you are ready. Have a great day!', timestamp: new Date(Date.now() - 172800000 + 7800000).toISOString(), state: 'ended' },
    ],
    llm_provider: 'openai',
    llm_model: 'gpt-4o',
    last_ai_message: 'No problem at all! Feel free to reach out whenever you are ready.',
  },
  {
    call_sid: 'CA102',
    phone_number: '+919876543203',
    state: 'ended',
    outcome: 'handoff',
    started_at: new Date(Date.now() - 259200000 + 10800000).toISOString(),
    ended_at: new Date(Date.now() - 259200000 + 12600000).toISOString(),
    duration_seconds: 1800,
    transcript: [
      { speaker: 'ai', text: 'Hello! Welcome to Elite Mentors. How may I assist you?', timestamp: new Date(Date.now() - 259200000 + 10800000).toISOString(), state: 'opening' },
      { speaker: 'user', text: 'I need a very specific mentor for blockchain development. Do you have someone?', timestamp: new Date(Date.now() - 259200000 + 10900000).toISOString() },
      { speaker: 'ai', text: 'Blockchain is a specialized area. Let me connect you with our technical program director who can match you with the right mentor. One moment please.', timestamp: new Date(Date.now() - 259200000 + 11000000).toISOString(), state: 'discovery' },
      { speaker: 'user', text: 'Okay, I will wait.', timestamp: new Date(Date.now() - 259200000 + 11100000).toISOString() },
      { speaker: 'ai', text: 'I am transferring you now. Our director Rajesh will be with you shortly.', timestamp: new Date(Date.now() - 259200000 + 11200000).toISOString(), state: 'close' },
    ],
    llm_provider: 'anthropic',
    llm_model: 'claude-3-sonnet',
    last_ai_message: 'I am transferring you now. Our director Rajesh will be with you shortly.',
  },
  {
    call_sid: 'CA103',
    phone_number: '+919876543204',
    state: 'ended',
    outcome: 'dropped',
    started_at: new Date(Date.now() - 345600000 + 14400000).toISOString(),
    ended_at: new Date(Date.now() - 345600000 + 14430000).toISOString(),
    duration_seconds: 30,
    transcript: [
      { speaker: 'ai', text: 'Hello! Thank you for calling Leadership Edge. How can I help?', timestamp: new Date(Date.now() - 345600000 + 14400000).toISOString(), state: 'opening' },
    ],
    llm_provider: 'groq',
    llm_model: 'llama-3.3-70b',
    last_ai_message: 'Hello! Thank you for calling Leadership Edge. How can I help?',
  },
  {
    call_sid: 'CA104',
    phone_number: '+919876543205',
    state: 'ended',
    outcome: 'booked',
    started_at: new Date(Date.now() - 432000000 + 18000000).toISOString(),
    ended_at: new Date(Date.now() - 432000000 + 19800000).toISOString(),
    duration_seconds: 1800,
    transcript: [
      { speaker: 'ai', text: 'Hi there! Welcome to Career Catalyst. What brings you here today?', timestamp: new Date(Date.now() - 432000000 + 18000000).toISOString(), state: 'opening' },
      { speaker: 'user', text: 'I am a fresher looking for my first job. Can you help?', timestamp: new Date(Date.now() - 432000000 + 18100000).toISOString() },
      { speaker: 'ai', text: 'Absolutely! We have a dedicated "First Steps" program for freshers. It covers resume building, interview skills, and job search strategy. What field are you targeting?', timestamp: new Date(Date.now() - 432000000 + 18200000).toISOString(), state: 'discovery' },
      { speaker: 'user', text: 'Software engineering. I am a CS graduate.', timestamp: new Date(Date.now() - 432000000 + 18300000).toISOString() },
      { speaker: 'ai', text: 'Perfect! We have placed over 1000 CS freshers in top companies. Our program includes mock interviews with real hiring managers. The fee is Rs 15,000 with a job guarantee.', timestamp: new Date(Date.now() - 432000000 + 18400000).toISOString(), state: 'pitch' },
      { speaker: 'user', text: 'That sounds good. How do I enroll?', timestamp: new Date(Date.now() - 432000000 + 18500000).toISOString() },
      { speaker: 'ai', text: 'Great choice! I am sending you the enrollment link via WhatsApp. You can also pay in 3 easy installments. Welcome to Career Catalyst!', timestamp: new Date(Date.now() - 432000000 + 18600000).toISOString(), state: 'close' },
    ],
    llm_provider: 'deepseek',
    llm_model: 'deepseek-chat',
    last_ai_message: 'Great choice! I am sending you the enrollment link via WhatsApp.',
  },
  {
    call_sid: 'CA105',
    phone_number: '+919876543206',
    state: 'ended',
    outcome: 'declined',
    started_at: new Date(Date.now() - 518400000 + 21600000).toISOString(),
    ended_at: new Date(Date.now() - 518400000 + 22800000).toISOString(),
    duration_seconds: 1200,
    transcript: [
      { speaker: 'ai', text: 'Hello! This is Peak Performance Coaching. How can I help you excel today?', timestamp: new Date(Date.now() - 518400000 + 21600000).toISOString(), state: 'opening' },
      { speaker: 'user', text: 'I heard about your executive coaching. What does it cost?', timestamp: new Date(Date.now() - 518400000 + 21700000).toISOString() },
      { speaker: 'ai', text: 'Our executive coaching program is a premium offering at Rs 1,50,000 for a 6-month engagement. It includes weekly 1-on-1 sessions with our senior coaches.', timestamp: new Date(Date.now() - 518400000 + 21800000).toISOString(), state: 'discovery' },
      { speaker: 'user', text: 'That is way too expensive. I was thinking more like Rs 20,000.', timestamp: new Date(Date.now() - 518400000 + 21900000).toISOString() },
      { speaker: 'ai', text: 'I understand. For your budget, we have a group coaching option at Rs 25,000 where you learn alongside 5 other executives. Would that work?', timestamp: new Date(Date.now() - 518400000 + 22000000).toISOString(), state: 'objection' },
      { speaker: 'user', text: 'No, I will look elsewhere. Thanks.', timestamp: new Date(Date.now() - 518400000 + 22100000).toISOString() },
    ],
    llm_provider: 'groq',
    llm_model: 'llama-3.3-70b',
    last_ai_message: 'I understand. For your budget, we have a group coaching option at Rs 25,000.',
  },
  {
    call_sid: 'CA106',
    phone_number: '+919876543207',
    state: 'ended',
    outcome: 'booked',
    started_at: new Date(Date.now() - 604800000 + 25200000).toISOString(),
    ended_at: new Date(Date.now() - 604800000 + 27000000).toISOString(),
    duration_seconds: 1800,
    transcript: [
      { speaker: 'ai', text: 'Namaste! Welcome to SkillForge. How may I assist you?', timestamp: new Date(Date.now() - 604800000 + 25200000).toISOString(), state: 'opening' },
      { speaker: 'user', text: 'I want to learn data science. Do you have a course?', timestamp: new Date(Date.now() - 604800000 + 25300000).toISOString() },
      { speaker: 'ai', text: 'Yes! Our Data Science Mastery program is one of our most popular offerings. It is a 16-week intensive with hands-on projects. Are you a beginner or do you have some experience?', timestamp: new Date(Date.now() - 604800000 + 25400000).toISOString(), state: 'discovery' },
      { speaker: 'user', text: 'I know some Python and statistics.', timestamp: new Date(Date.now() - 604800000 + 25500000).toISOString() },
      { speaker: 'ai', text: 'That is a great foundation! You can join our intermediate batch starting next Monday. The course fee is Rs 45,000 and we offer placement assistance.', timestamp: new Date(Date.now() - 604800000 + 25600000).toISOString(), state: 'pitch' },
      { speaker: 'user', text: 'Sounds good. Book me a seat.', timestamp: new Date(Date.now() - 604800000 + 25700000).toISOString() },
      { speaker: 'ai', text: 'Excellent! Your seat is reserved. Please complete the payment within 24 hours to confirm. Welcome to SkillForge!', timestamp: new Date(Date.now() - 604800000 + 25800000).toISOString(), state: 'close' },
    ],
    llm_provider: 'openai',
    llm_model: 'gpt-4o',
    last_ai_message: 'Excellent! Your seat is reserved. Please complete the payment within 24 hours.',
  },
  {
    call_sid: 'CA107',
    phone_number: '+919876543208',
    state: 'ended',
    outcome: 'dropped',
    started_at: new Date(Date.now() - 691200000 + 28800000).toISOString(),
    ended_at: new Date(Date.now() - 691200000 + 28860000).toISOString(),
    duration_seconds: 60,
    transcript: [
      { speaker: 'ai', text: 'Hello! Thank you for calling InnoMinds Coaching.', timestamp: new Date(Date.now() - 691200000 + 28800000).toISOString(), state: 'opening' },
    ],
    llm_provider: 'groq',
    llm_model: 'llama-3.3-70b',
    last_ai_message: 'Hello! Thank you for calling InnoMinds Coaching.',
  },
  {
    call_sid: 'CA108',
    phone_number: '+919876543209',
    state: 'ended',
    outcome: 'handoff',
    started_at: new Date(Date.now() - 777600000 + 32400000).toISOString(),
    ended_at: new Date(Date.now() - 777600000 + 34200000).toISOString(),
    duration_seconds: 1800,
    transcript: [
      { speaker: 'ai', text: 'Hello! Welcome to BrightSparks Academy. How can I help?', timestamp: new Date(Date.now() - 777600000 + 32400000).toISOString(), state: 'opening' },
      { speaker: 'user', text: 'I need coaching for my entire sales team. About 20 people.', timestamp: new Date(Date.now() - 777600000 + 32500000).toISOString() },
      { speaker: 'ai', text: 'That is a substantial team! We offer corporate sales training programs. Let me connect you with our corporate sales head who can design a custom program for you.', timestamp: new Date(Date.now() - 777600000 + 32600000).toISOString(), state: 'discovery' },
      { speaker: 'user', text: 'Yes, please connect.', timestamp: new Date(Date.now() - 777600000 + 32700000).toISOString() },
    ],
    llm_provider: 'anthropic',
    llm_model: 'claude-3-sonnet',
    last_ai_message: 'Let me connect you with our corporate sales head who can design a custom program.',
  },
  {
    call_sid: 'CA109',
    phone_number: '+919876543211',
    state: 'ended',
    outcome: 'booked',
    started_at: new Date(Date.now() - 864000000 + 36000000).toISOString(),
    ended_at: new Date(Date.now() - 864000000 + 37800000).toISOString(),
    duration_seconds: 1800,
    transcript: [
      { speaker: 'ai', text: 'Hello! This is Zenith Learning. How can I help you today?', timestamp: new Date(Date.now() - 864000000 + 36000000).toISOString(), state: 'opening' },
      { speaker: 'user', text: 'I want to prepare for my GMAT exam. Do you have coaching?', timestamp: new Date(Date.now() - 864000000 + 36100000).toISOString() },
      { speaker: 'ai', text: 'Yes, we have a comprehensive GMAT prep program! It includes quant, verbal, and AWA sections with 10 full-length mock tests. When is your exam?', timestamp: new Date(Date.now() - 864000000 + 36200000).toISOString(), state: 'discovery' },
      { speaker: 'user', text: 'In 3 months. I need at least 720.', timestamp: new Date(Date.now() - 864000000 + 36300000).toISOString() },
      { speaker: 'ai', text: '3 months is a great timeline for a 720+ score. Our intensive program has helped 200+ students score 720+. The course starts at Rs 55,000. Shall I book a diagnostic test for you?', timestamp: new Date(Date.now() - 864000000 + 36400000).toISOString(), state: 'pitch' },
      { speaker: 'user', text: 'Yes, book the diagnostic test.', timestamp: new Date(Date.now() - 864000000 + 36500000).toISOString() },
      { speaker: 'ai', text: 'Done! Your diagnostic test is scheduled for this Saturday at 10 AM. You will receive all details via email. All the best!', timestamp: new Date(Date.now() - 864000000 + 36600000).toISOString(), state: 'close' },
    ],
    llm_provider: 'deepseek',
    llm_model: 'deepseek-chat',
    last_ai_message: 'Done! Your diagnostic test is scheduled for this Saturday at 10 AM.',
  },
]

export const mockBattleCard: BattleCard = {
  business_name: 'Career Launchpad',
  owner_name: 'Rahul Sharma',
  service_description: 'Premium career coaching and mentorship for Indian professionals looking to accelerate their careers, switch industries, or land leadership roles. We offer 1-on-1 coaching, resume optimization, interview preparation, and salary negotiation training.',
  pricing: 'Rs 25,000 for 8 sessions (3 months) | Rs 45,000 for 16 sessions (6 months)',
  session_duration: '60 minutes per session',
  ideal_client: 'Working professionals with 3-10 years experience in IT, consulting, or banking who want to transition to leadership roles or switch careers',
  calendar_link: 'https://calendly.com/careerlaunchpad/consultation',
}

export const mockObjections: Objection[] = [
  { id: '1', trigger: 'too expensive', response: 'I understand budget is a concern. Many of our clients felt the same way initially. We offer flexible EMI options starting at Rs 4,000/month. Would that help?', category: 'price' },
  { id: '2', trigger: 'need to think about it', response: 'Of course, this is an important decision. To help you think it through, may I ask what specific aspect you would like to evaluate? I can also share some case studies of professionals like you who have benefited.', category: 'stall' },
  { id: '3', trigger: 'will compare with others', response: 'That is a smart approach. While you are comparing, I would suggest looking at three things: coach credentials, success rate, and post-program support. We excel in all three. Would you like to know why?', category: 'competition' },
  { id: '4', trigger: 'not the right time', response: 'I understand timing is important. In our experience, professionals who wait often miss key opportunities. Our program has limited seats each month. Would it help if I reserved a spot that you can confirm within 48 hours?', category: 'stall' },
  { id: '5', trigger: 'will ask my family', response: 'That is wise to consult your family. Would you like me to send a brief program overview that you can share with them? It includes the curriculum, testimonials, and ROI breakdown.', category: 'authority' },
  { id: '6', trigger: 'do not need coaching', response: 'Many successful professionals feel the same way. However, even Sachin Tendulkar had a coach. A coach helps you see blind spots and accelerates your growth. Would you be open to a free 15-minute assessment to identify any gaps?', category: 'need' },
]

export function generateMockAnalytics(): Analytics {
  const daily: DailyAnalytics[] = []
  for (let i = 29; i >= 0; i--) {
    const date = new Date(Date.now() - i * 86400000).toISOString().split('T')[0]
    const total = Math.floor(Math.random() * 15) + 3
    daily.push({
      date,
      total_calls: total,
      booked: Math.floor(total * 0.35),
      declined: Math.floor(total * 0.25),
      handoff: Math.floor(total * 0.15),
      dropped: total - Math.floor(total * 0.35) - Math.floor(total * 0.25) - Math.floor(total * 0.15),
      avg_duration: Math.floor(Math.random() * 1200) + 300,
      avg_latency_ms: Math.floor(Math.random() * 150) + 50,
    })
  }

  const totalCalls = daily.reduce((s, d) => s + d.total_calls, 0)
  const bookedCalls = daily.reduce((s, d) => s + d.booked, 0)

  return {
    summary: {
      total_calls: totalCalls,
      conversion_rate: Math.round((bookedCalls / totalCalls) * 100),
      avg_duration: Math.round(daily.reduce((s, d) => s + d.avg_duration, 0) / daily.length),
      top_objection: 'Too expensive',
    },
    daily,
    objections: [
      { name: 'Too expensive', count: 45 },
      { name: 'Need to think', count: 32 },
      { name: 'Will compare', count: 28 },
      { name: 'Not right time', count: 22 },
      { name: 'Need family approval', count: 18 },
      { name: 'Do not need coaching', count: 15 },
    ],
    provider_usage: [
      { provider: 'Groq', count: 180 },
      { provider: 'OpenAI', count: 45 },
      { provider: 'Anthropic', count: 25 },
      { provider: 'DeepSeek', count: 30 },
    ],
    response_times: daily.flatMap(d => [
      { timestamp: d.date + 'T09:00:00Z', latency_ms: d.avg_latency_ms + Math.floor(Math.random() * 50), provider: 'Groq' },
      { timestamp: d.date + 'T15:00:00Z', latency_ms: d.avg_latency_ms + Math.floor(Math.random() * 80), provider: 'Groq' },
    ]),
  }
}

export const mockProviders: LLMProvider[] = [
  { id: 'groq', name: 'Groq', model: 'llama-3.3-70b', latency_ms: 85, api_key_set: true, description: 'Fastest inference with Llama models', pros: ['Fastest', '<100ms latency', 'Great for voice', 'Free tier available'] },
  { id: 'openai', name: 'OpenAI', model: 'gpt-4o', latency_ms: 250, api_key_set: true, description: 'Reliable GPT-4 models with excellent quality', pros: ['Reliable', 'Good quality', 'Moderate cost', 'Great tool use'] },
  { id: 'anthropic', name: 'Anthropic', model: 'claude-3-sonnet', latency_ms: 350, api_key_set: false, description: 'Best reasoning capabilities for complex objections', pros: ['Best reasoning', 'Excellent for objections', 'Long context', 'High quality'] },
  { id: 'deepseek', name: 'DeepSeek', model: 'deepseek-chat', latency_ms: 400, api_key_set: false, description: 'Budget-friendly option with good async performance', pros: ['Cheapest', 'Good for async', 'Budget friendly', 'Decent quality'] },
]
